# Generated by Django 5.0.6 on 2024-05-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_remove_user_is_verified_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
