# Generated by Django 5.0.6 on 2024-05-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_version_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication_sign',
            field=models.BooleanField(default=False, verbose_name='Признак публикации'),
        ),
    ]
