# Generated by Django 5.0.6 on 2024-05-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_publication_sign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_publication_sign', 'can edit publication sign')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
