# Generated by Django 5.0.6 on 2024-05-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_publication_sign', 'can edit publication sign'), ('can_edit_category', 'can edit category'), ('can_edit_description', 'can edit description')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
