# Generated by Django 5.0.6 on 2024-05-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='user_owner',
        ),
    ]
